### ISSUE TITLE
GitHub Url Docs

### ISSUE THREAD

**Issue by alanisaac** [ldd/gatsby-source-github-api#18]
EDIT: I can't read -- at first I thought the GitHub url was hard-coded, but I see now it's configurable.  

Could the url parameter be added to the examples in the docs?  I'm using this with GitHub Enterprise.

**Comment by ldd** [comment]
You were absolutely right. I've made the changes. 

Thanks!

**Comment by ldd** [comment]
I should probably rewrite the readme at some point, add a table for each configuration option, etc. 

I'll think about it.
