### ISSUE TITLE
Getting contributors on each repostirory?

### ISSUE THREAD

**Issue by Blakeinstein** [ldd/gatsby-source-github-api#24]
As far as I am aware, this is not possible with graphql currently, and the default REST Api (v3) is necesssary. How would one go about adding the same here?

I know its necessarily not an issue with this plugin. But I would love to know.

**Comment by ldd** [comment]
It seems you [are right](https://github.community/t/graphql-get-repository-contributors/14422/7).

It would be outside of the scope of this project, but if it were me, i would just write a short bash script file that fetches this with the default REST api. Then I'd use [jq](https://stedolan.github.io/jq/) to manipulate the result and write it to a JSON file.

you could probably do it in a git hook.

Let me know what you end up doing! :D

**Comment by Blakeinstein** [comment]
One solution I can think of is to just make the graphql queries seperately from gatsby and then once i had the repositories list, I can then get contributors and write the result to a json file. And use the json file in the build process. 
This should also allow me to add dummy data, as another issue I have right now is with other people contributing to the code. They may not have an api key with same access level, resulting in errors on the queries and also I cannot test pull requests with a test build process as the repo secrets are not made available to PRs

**Comment by Blakeinstein** [comment]
This is what I ended up doing, fetching said data to json at vuild time and loading that.
Thanks!
