### ISSUE TITLE
Gatsby v3.x compatibility

### ISSUE THREAD

**Issue by erikbrgn** [ldd/gatsby-source-github-api#26]
On migrating a Gatsby 2.x project to 3.x, I ran into some issues with this plugin. After some debugging I found that boundActionCreators was removed in the update and actions should now be used in its place.

See [this](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#removal-of-boundactioncreators) for reference.

**Comment by bradgarropy** [comment]
Hey @erikbrgn I had the same issue!

```
Cannot destructure property 'createNode' of 'boundActionCreators' as it is undefined.
```

How did you solve the problem?

**Comment by erikbrgn** [comment]
@bradgarropy I solved it by updating to the latest version of the repo. Unfortunately, the working version hasn't been published to npm yet it seems, so I changed the entry in package.json to point to the latest version of this repo.

**Comment by bradgarropy** [comment]
Thanks! I saw a [related PR](https://github.com/ldd/gatsby-source-github-api/pull/25) and left a [few comments](https://github.com/ldd/gatsby-source-github-api/pull/25#issuecomment-815407001) over there.

I fixed it by installing a [fork](https://www.npmjs.com/package/@bellistic/gatsby-source-github-api) that is ready for Gatsby `v3`.

**Comment by ldd** [comment]
It's published on NPM now.

**Comment by bradgarropy** [comment]
Confirmed, everything is working as expected with `v1.0.0`. Thank you @ldd!
