### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by pomle** [ldd/gatsby-source-github-api#38]
Can this library run multiple queries?

If it can not, how are you be able to fetch repo information from arbitrary chosen repos? 
Just trying to figure out if I am blind.

Thanks!

**Comment by ldd** [comment]
It depends on what you mean by multiple queries.

I do know what fetching info from many repos is supported on GraphQL:

https://github.com/octokit/request.js/issues/204

from that link:
```
fragment repoProperties on Repository {
  nameWithOwner
  description
}

{
  repo1: repository(owner: "ldd", name: "gatsby-source-github-api") {
    ...repoProperties
  }
  repo2: repository(owner: "octokit", name: "graphql.js") {
    ...repoProperties
  }
}
```

**Comment by pomle** [comment]
That should work. Thanks
